name: 'exploiut-prod'

services:
  database:
    image: mariadb:11.8
    environment:
      - MARIADB_ROOT_PASSWORD=iwxgPRZPvFFWESGNYRKTTFL3
      - MARIADB_USER=exploit-usr
      - MARIADB_PASSWORD=A9v6R4p2EtYF3r5HVUhZQe
      - MARIADB_DATABASE=exploriut
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-net
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s 

  api-server:
    image: exploriut/app
    build: ../../
    depends_on:
      nosqldatabase:
        condition: service_healthy
    restart: always
    working_dir: /usr/src/app
    configs:
      - source: spring
        target: /root/application.properties
        mode: 0440
      - source: ehcache
        target: /root/ehcache.xml
        mode: 0440
    volumes:
      - file-data:/data
      - api-server-cache:/var/spring-ehcache
    networks:
      - db-net
    ports:
      - 127.0.0.1:8080:8080
    command: --spring.config.location=/root/application.properties

volumes:
  db-data:
  file-data:
  api-server-cache:

networks:
  db-net:

configs:
  spring:
    file: api-prod.properties
  ehcache:
    file: ehcache-prod.xml