name: 'exploiut-demo'

services:
  database:
    image: mariadb:11.8
    environment:
      - MARIADB_ROOT_PASSWORD=LRNSriqNtuvomX6
      - MARIADB_USER=exploriutuser
      - MARIADB_PASSWORD=A35Jfzeghh23
      - MARIADB_DATABASE=exploriut
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-net
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s 

  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    networks:
      - db-net
    ports:
      - 127.0.0.1:1080:1080/tcp

  api-server:
    image: exploriut/app
    build: ../../
    cpu_count: 2
    mem_limit: 512m
    depends_on:
      nosqldatabase:
        condition: service_healthy
    environment:
        VALIDATION_URL: http://localhost:3000/validate
    restart: always
    configs:
      - source: spring
        target: /root/application.properties
        mode: 0440
      - source: ehcache
        target: /root/ehcache.xml
        mode: 0440
    volumes:
      - /repertoire-donnees:/data
      - api-server-cache:/var/spring-ehcache
    networks:
      - db-net
    ports:
      - 127.0.0.1:8080:8080
    command: --spring.config.location=/root/application.properties

volumes:
  db-data:
  file-data:
  api-server-cache:

networks:
  db-net:

configs:
  spring:
    file: api-demo.properties
  ehcache:
    file: ehcache-demo.xml